apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-prometheus
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e3125e5256932707::fsap-08f470041507945eb