apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master  # Track the 'master' branch instead of 'main'
    path: kube/volumes/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # Automatically create the staging namespace when syncing

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master  # Track the 'master' branch instead of 'main'
    path: kube/volumes/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated: {}  # No automatic sync for production, manual sync after staging approval
    syncOptions:
      - CreateNamespace=false  # Do not automatically create the production namespace
  hooks:
    - exec:
        command: ["/bin/sh", "-c", "echo 'Production namespace will be created after manual approval from Staging'"]
      syncPolicy:
        manual: true  # Trigger manual approval for production deployment
    # You can add more hooks here if needed for manual approvals.

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master  # Track the 'master' branch instead of 'main'
    path: kube/application/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true  # Automatically create the staging namespace when syncing
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master  # Track the 'master' branch instead of 'main'
    path: kube/application/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated: {}  # Sync will happen manually for production
    syncOptions:
      - CreateNamespace=false  # Do not automatically create the production namespace
