apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/volumes/staging  # Uses staging-specific storage setup
  destination:
    server: https://kubernetes.default.svc
    namespace: staging  # Storage applies to staging namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: "0"  # Deploy storage before the app

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/volumes/production  # Uses production-specific storage setup
  destination:
    server: https://kubernetes.default.svc
    namespace: production  # Storage applies to production namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: "0"  # Deploy storage before the app

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/aplication/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging  # Deploys to staging first
  syncPolicy:
    automated: {}  # No auto-sync (manual approval for production)
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  syncWave: "1"  # Deploy after staging storage

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/aplication/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production  # Deploys to production after approval
  syncPolicy:
    automated: {}  # Requires manual approval
    syncOptions:
      - CreateNamespace=true
  syncWave: "2"  # Deploy after production storage and staging confirmation
