# EFS Storage for Staging
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master  # Ensuring it pulls from master
    path: kube/volumes/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: "0"  # Ensures storage is deployed before the app

---
# EFS Storage for Production
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master
    path: kube/volumes/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: "0"

---
# Status Page App for Staging (Auto-deploys new images)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master
    path: kube/aplication/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  syncWave: "1"

---
# Status Page App for Production (Manual approval required)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: master
    path: kube/aplication/production
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated: {}  # Manual approval required
    syncOptions:
      - CreateNamespace=true
  syncWave: "2"  # Deploy after QA approval
