apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/application  # Path to your manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: staging  # Starts in the staging namespace
  syncPolicy:
    automated: {}  # No auto-sync (requires manual approval for production)
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
  syncWave: "1"  # Ensure app deploys after storage
---
# Deploy the same app to production after QA approval
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: status-page-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/application
  destination:
    server: https://kubernetes.default.svc
    namespace: production  # Moves to production after approval
  syncPolicy:
    automated: {}  # Requires manual approval
    syncOptions:
      - CreateNamespace=true
  syncWave: "2"  # Deploy after staging is confirmed
---
# Ensure EFS storage is deployed first
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efs-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: cleaning
    path: kube/volumes
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  syncWave: "0"  # Deploy storage first
