apiVersion: argoproj.io/v1
kind: Application
metadata:
  name: status-page-app-production
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    manual: {}  # Manual sync enabled
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: neta-test-this
    path: kube/production
  sources:
    - repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
      targetRevision: neta-test-this
      path: kube/production/storage
    - repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
      targetRevision: neta-test-this
      path: kube/production/application
    - repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
      targetRevision: neta-test-this
      path: kube/production/ingress
