apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
    targetRevision: neta-test-this
    path: kube/staging/storage
  sources:
    - repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
      targetRevision: neta-test-this
      path: kube/staging/storage
    - repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
      targetRevision: neta-test-this
      path: kube/staging/application
    - repoURL: https://github.com/NetaAviv/neta-frendrick-final-project.git
      targetRevision: neta-test-this
      path: kube/staging/ingress
