apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-server
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-server
        # image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/neta-fred/final-project:nginx
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/neta-fred/final-project:nginx-test
        # imagePullPolicy: Always
        # volumeMounts:
        #   - name: config-volume
        #     mountPath: /etc/nginx/nginx.conf
        #     subPath: nginx.conf
        command: ["/bin/bash", "-c"]
        args:
           - |

              echo "📁 Creating NGINX directory structure...";
              mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled;

              # echo "🔐 Creating self-signed certificate...";
              # openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
              #   -subj "/C=US/ST=None/L=None/O=K8S/CN=localhost" \
              #   -keyout /etc/ssl/private/status-page.key \
              #   -out /etc/ssl/certs/status-page.crt;

              echo "🔗 Linking config into sites-enabled...";
              rm -f /etc/nginx/sites-enabled/default;
              ln -s /etc/nginx/sites-available/status-page.conf /etc/nginx/sites-enabled/status-page.conf;

              echo "🚀 Starting NGINX...";
              nginx -g 'daemon off;'
              
        # command: ["nginx", "-g", "daemon off;"]
        # ports:
        # - containerPort: 80
        # - containerPort: 443
      # volumes:
      #   - name: config-volume
      #     configMap:
      #       name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:992382545251:certificate/fcf5e0fa-9c8c-444e-8ba1-957231dad5ae
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: nginx-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer
