apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: myapp
spec:
  restartPolicy: Never
  containers:
    - name: nginx-test
      image: test_nginx
      imagePullPolicy: Never
      # command: ["nginx", "-g", "daemon off;"]

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server-test
spec:
  selector:
    app: myapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30006
  type: NodePort