
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  restartPolicy: Never
  containers:
    - name: app
      image: my-image:latest
      imagePullPolicy: Never
      command: ["/bin/bash", "-c"]
      args:
        - echo starting;
          bash /opt/status-page/upgrade.sh ;
          source /opt/status-page/venv/bin/activate &&
          export PYTHONPATH=/opt/status-page/statuspag &&
          gunicorn -c /opt/status-page/gunicorn.py statuspage.wsgi:application --chdir /opt/status-page/statuspage
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-server
spec:
  selector:
    app: status-page
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
