apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
  labels:
    app: status-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      containers:
        - name: status-page-latest
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/neta-fred/final-project:status-test
          # imagePullPolicy: Never
          # volumeMounts:
          # - name: efs-volume
          #   mountPath: /opt/status-page
          command: ["/bin/bash", "-c"]
          args:
            - echo starting;
              mkdir -p /var/log/supervisor /etc/supervisor/conf.d  ;
              bash /opt/status-page/upgrade.sh ;
              cd /opt/status-page &&
              source /opt/status-page/venv/bin/activate &&
              export PYTHONPATH=/opt/status-page/statuspag &&
              /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisor.conf
      # volumes:
      #   - name: efs-volume
      #     persistentVolumeClaim:
      #       claimName: efs-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: status-page-server
spec:
  selector:
    app: status-page
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP

