apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap  # ✅ Fix: Enable EFS Access Point mode
  fileSystemId: fs-07a963a2761172d90  # ✅ Your EFS File System ID
  accessPointId: fsap-03051621616e3f2b1  # ✅ Your EFS Access Point ID
  directoryPerms: "777"  # (Optional) Permissions for root directory
mountOptions:
  - tls
reclaimPolicy: Retain
