version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    environment:
      REDIS_HOST: redis-server
      DB_USERNAME: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    restart: "no"  # Prevents auto-restarting after script runs
    depends_on:
      - redis
    networks:
      - mynetwork
    ports:
      - "8000:8000"
      - "8001:8001"
    hostname: status-page-server
    volumes:
      - /test/opt:/opt
    command: >
      /bin/bash -c "
      while true; do sleep 60; done"
#      echo 'showing my files' &&
#      ls /opt &&
#      echo 'Running upgrade.sh...' &&
#      bash /opt/status-page/upgrade.sh &&
#      source /opt/status-page/venv/bin/activate &&
#      python3 /opt/status-page/statuspage/manage.py collectstatic --noinput &&
#      echo 'Setting permissions for static files...' &&
#      chmod -R 755 /opt/status-page/statuspage/static &&
#      echo 'Starting gunicorn...' &&
#      export PYTHONPATH=/opt/status-page/statuspag &&
#      gunicorn -c /opt/status-page/gunicorn.py statuspage.wsgi:application --chdir /opt/status-page/statuspage"

networks:
  mynetwork:
    driver: bridge
