apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-production
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-production
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02bded1456fa64b56::fsap-014979be07e8edbaf
