apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-production
  namespace: production
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc-production  # ✅ Directly reference the PV instead of using storageClassName
