apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-grafana
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0e3125e5256932707::fsap-0af2c8df60db75146