apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-efs-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-prometheus
  volumeName: prometheus-pv      
  resources:
    requests:
      storage: 5Gi