apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-efs-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-grafana
  resources:
    requests:
      storage: 2Gi
  volumeName: grafana-pv