apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
  labels:
    app: status-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      securityContext:
        runAsUser: 1000  # Non-root user ID
        runAsGroup: 1000  # Non-root group
        fsGroup: 1000  # Ensures volume permissions are correct
      containers:
        - name: status-page-latest
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/neta-fred/final-project:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false  # Prevent privilege escalation
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true  # Prevent writing to root filesystem
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc-production

---
apiVersion: v1
kind: Service
metadata:
  name: status-page-server
spec:
  selector:
    app: status-page
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
