apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
  labels:
    app: status-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
  template:
    metadata:
      labels:
        app: status-page
    spec:
      containers:
        - name: status-page-latest
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/neta-fred/final-project:app
          command: ["/bin/bash", "-c"]
          args:
            - echo starting;
              bash /opt/status-page/upgrade.sh ;
              source /opt/status-page/venv/bin/activate &&
              export PYTHONPATH=/opt/status-page/statuspag &&
              gunicorn -c /opt/status-page/gunicorn.py statuspage.wsgi:application --chdir /opt/status-page/statuspage
          volumeMounts:
            - name: efs-storage
              mountPath: /mnt/efs/opt/status-page  # Mount the EFS volume at this path inside your container
      volumes:
        - name: efs-storage
          persistentVolumeClaim:
            claimName: efs-pvc  # Reference the PVC you created
#          volumeMounts:
#            - name: ebs-volume
#              mountPath: /opt/status-page  # Adjust this to the appropriate path inside the container where you want to mount the volume
#      volumes:
#        - name: ebs-volume
#          persistentVolumeClaim:
#            claimName: ebs-pvc  # Reference your PVC here
---
apiVersion: v1
kind: Service
metadata:
  name: status-page-server
spec:
  selector:
    app: status-page
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
