apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: ubuntu
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: efs-storage
      mountPath: /mnt/efs/
  volumes:
  - name: efs-storage
    persistentVolumeClaim:
      claimName: efs-pvc
  restartPolicy: Never