version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    restart: "no"  # ⬅️ Prevents auto-restarting after script runs
    depends_on:
      - redis  # Ensure Redis starts first
    networks:
      - mynetwork
    environment:
      REDIS_HOST: redis-server  # Pass Redis hostname to the app
    command: ["/bin/bash", "-c", "sleep 5 && ./status-page/upgrade.sh"]

networks:
  mynetwork:
    driver: bridge
