version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    restart: "no"  # ⬅️ Prevents auto-restarting after script runs
    depends_on:
      - redis  # Ensure Redis starts first
    networks:
      - mynetwork
    environment:
      REDIS_HOST: redis-server  # Pass Redis hostname to the app
    ports:
      - "8000:8000"
      - "8001:8001"
    hostname: status-page-server
    command: >
      /bin/bash -c "
      echo 'Running upgrade.sh...' &&
      bash /opt/status-page/upgrade.sh &&
      echo 'starting gunicorn...' &&      
      source /opt/status-page/venv/bin/activate &&
      export PYTHONPATH=/opt/status-page/statuspag &&
      gunicorn -c /opt/status-page/gunicorn.py statuspage.wsgi:application --chdir /opt/status-page/statuspage &&
      cd /opt/status-page/statuspage &&
      echo 'Starting Django server...' &&
      cd /opt/status-page/statuspage &&
      python3 manage.py runserver 0.0.0.0:8000 --insecure"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - status-page
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
