version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    restart: "no"  # ⬅️ Prevents auto-restarting after script runs
    depends_on:
      - redis  # Ensure Redis starts first
    networks:
      - mynetwork
    environment:
      REDIS_HOST: redis-server  # Pass Redis hostname to the app

    command: >
      /bin/bash -c "
      echo 'Running upgrade.sh...' &&
      bash /opt/status-page/upgrade.sh &&
      echo 'Creating superuser...' &&
      source /opt/status-page/venv/bin/activate &&
      cd /opt/status-page/statuspage &&
      echo 'Starting Django server...' &&
      python3 manage.py runserver 0.0.0.0:8000 --insecure"

networks:
  mynetwork:
    driver: bridge
