version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    hostname: redis-server

  status-page:
    build: .
    container_name: status-page
    restart: "no"  # ⬅️ Prevents auto-restarting after script runs
    depends_on:
      - redis  # Ensure Redis starts first
    networks:
      - mynetwork
    environment:
      REDIS_HOST: redis-server  # Pass Redis hostname to the app
    ports:
      - "8000:8000"
      - "8001:8001"
    hostname: status-page-server
    volumes:
      - static_files:/opt/status-page/statuspage/static

    command: >
      /bin/bash -c "
      echo 'Running upgrade.sh...' &&
      bash /opt/status-page/upgrade.sh &&
      source /opt/status-page/venv/bin/activate &&
      python3 /opt/status-page/statuspage/manage.py collectstatic --noinput &&
      echo 'Setting permissions for static files...' &&
      chmod -R 755 /opt/status-page/statuspage/static &&
      echo 'starting gunicorn...' &&      
      export PYTHONPATH=/opt/status-page/statuspag &&
      gunicorn -c /opt/status-page/gunicorn.py statuspage.wsgi:application --chdir /opt/status-page/statuspage"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - status-page
    networks:
      - mynetwork
    volumes:
      - static_files:/opt/status-page/statuspage/static

networks:
  mynetwork:
    driver: bridge

volumes:
  static_files: 