pipeline {
    agent any

    options {
        skipDefaultCheckout()
    }

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm
                    def changedFiles = sh(script: "git diff --name-only HEAD~1", returnStdout: true).trim().split('\n')
                    
                    if (!changedFiles.any { it.startsWith('stuff/opt/status-page/') }) {
                        echo "No changes in 'stuff/opt/status-page/'. Skipping build."
                        currentBuild.result = 'ABORTED'
                        return
                    }
                    echo "Saw changes in the stuff/opt/status-page path!"
                }
            }
        }

        stage('Test Node Connection & Docker Access') {
            agent { label 'ubuntu-node' } // Use the new node
            steps {
                script {
                    echo "Connected to testing server!"
                    def dockerOutput = sh(script: "docker ps", returnStatus: true)

                    if (dockerOutput == 0) {
                        echo "Was allowed to use Docker!"
                    } else {
                        error("Docker access failed! Check permissions.")
                    }
                }
            }
        }
    }
}
