apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc-staging
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: efs-sc-staging  # ✅ Directly reference the PV instead of using storageClassName
