apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-staging
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc-staging 
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02bded1456fa64b56::fsap-0d9a2275fa4292c91
